server:
  address: localhost
  port: 8689

logging:
  level:
    root: info
    lsh.*: debug
    jdbc :
      # 쿼리 로그 관련 설정
      # jdbc.sqlonly - SQL 문을 보여준다.
      # jdbc.sqltiming - SQL 문과 이 SQL 문을 수행하는 시간(ms)을 같이 보여준다.
      # jdbc.audit - ResultSet 을 제외한 모든 JDBC 호출 정보를 로그로 보여준다. 상당히 많은 양의 로그가 나오기 때문에 권장하지 않음.
      # jdbc.resultset - ResultSet 을 포함한 모든 JDBC 호출 정보를 로그로 보여준다. audit 처럼 많은 로그가 나오기 때문에 권장하지 않음.
      # jdbc.resultsettable - SQL 의 결과로 조회된 데이터를 table 형태로 로그를 보여준다.
      # jdbc.connection - DB 연결, 연결 해제와 관련된 로그를 보여준다
      sqlonly : info
      sqltiming : off
      resultsettable : info
      audit : off
      resultset : off
      connection : off

  # config: classpath:logback-${spring.profiles.active}.xml
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: classpath:/
    livereload:
      enabled: true
  mustache:
    servlet:
      cache: false






